/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/pydantic/_internal/_config.py:295: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: data did not match any variant of untagged enum ChatCompletionRequestContent at line 1 column 416
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Error occurred: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/bjy15364883518/mofa/python/mofa/agent_build/base/base_agent.py", line 236, in wrapper
    func(*args, **kwargs)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 40, in run
    value = searchEngine.extract_keywords(user_input)
  File "/home/bjy15364883518/mofa/python/agent-hub/analyse-agent/agent/main.py", line 25, in extract_keywords
    response = self.client.chat.completions.create(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1242, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 919, in request
    return self._request(
  File "/home/bjy15364883518/anaconda3/envs/mofa/lib/python3.10/site-packages/openai/_base_client.py", line 1023, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error_msg': 'Invalid Parameters. Multiple 422 errors detected. Please wait for 1 minute before trying again.'}
